- name: include vars
  include_vars:
    file: 'main.yml'
    name: 'Mac'

- name: homebrew update
  homebrew:
    update_homebrew: no

- name: add homebrew tap repository
  homebrew_tap:
    tap: '{{ item }}'
    state: present
  with_items: '{{ Mac.vars.homebrew_taps }}'

- name: homebrew packages install
  homebrew:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
  with_items: '{{ Mac.vars.homebrew_packages }}'

- name: homebrew caks packages install
  homebrew_cask:
    name: '{{ item.name }}'
    state: 'installed'
  environment:
    HOMEBREW_CASK_OPTS: '--appdir=/Applications'
  with_items: '{{ Mac.vars.homebrew_cask_packages }}'