vars:
  # homebrew_taps:
  #  - homebrew/dupes

  homebrew_packages:
    - { name: autoconf }
    - { name: automake }
    - { name: curl }
    - { name: cmake }
    - { name: gcc }
    - { name: git }
    - { name: imagemagick }
    - { name: nkf }
    - { name: openssl }
    - { name: peco }
    - { name: tree }
    - { name: vim, install_options: with-lua }
    - { name: wget }
    - { name: zsh, install_options: disable-etcdir }

  homebrew_cask_packages:
    - { name: 1password }
    - { name: 1password-cli }
    - { name: alfred }
    - { name: coteditor }
    - { name: docker }
    - { name: gimp }
    - { name: google-chrome }
    - { name: google-japanese-ime }
    - { name: iterm2 }
    - { name: karabiner-elements }
    - { name: microsoft-office }
    - { name: pycharm }
    - { name: slack }
    - { name: visual-studio-code }
    - { name: vivaldi }
    - { name: xquartz }
    - { name: zoomus }
