- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/dupes
      - homebrew/science
      - caskroom/cask
      - caskroom/versions
      - homebrew/binary

    homebrew_packages:
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: git }
      - { name: zsh, install_options: disable-etcdir }
      - { name: wget }
      - { name: curl }
      - { name: cmake }
      - { name: autoconf }
      - { name: automake }
      - { name: tree }
      - { name: nkf }
      - { name: tig }
      - { name: gcc }
      - { name: imagemagick }
      - { name: libjpeg }
      - { name: libpng }
      - { name: libtiff }
      - { name: libtool }
      - { name: pkg-config }
      - { name: qt5 }
      - { name: readline }
      - { name: sl }
      - { name: tbb }
      - { name: xz }
      - { name: vim, install_options: with-lua }
      - { name: peco }
      - { name: httperf }
      - { name: autobench }

    homebrew_cask_packages:
      - { name: google-chrome }
      - { name: vivaldi }
      # - { name: airmail-beta }
      - { name: iterm2 }
      # - { name: todoist }
      - { name: 1password }
      # - { name: calibre }
      # - { name: kindle}
      - { name: docker }
      - { name: zoomus }
      - { name: google-japanese-ime }
      - { name: coteditor }
      - { name: slack }
      - { name: karabiner-elements }
      # - { name: mactex }
      # - { name: duet }
      # - { name: sourcetree }
      - { name: alfred }
      - { name: xquartz }
      # - { name: vlc }
      - { name: gimp }
      # - { name: discord }

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes
 
    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'
 
    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      # ※1 GUIツールをインストールする場所を `/Application` に固定
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'
 
    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'
 
